
[[https://melpa.org/#/guess-language][file:https://melpa.org/packages/guess-language-badge.svg]]

* guess-language: Emacs minor mode for robust language detection as you type

*tl;dr:* Emacs minor mode that detects the language of what you're typing.  Automatically switches spell checker and typo-mode.  Uses a robust algorithm that works with many languages.  Can handle multiple languages in one document.

-----

I write a lot of text in multiple languages and was getting tired of constantly having to switch the dictionary of my spell-checker.  In true Emacs spirit, I decided to dust off my grandpa's parentheses and wrote some code to address this problem.  The result is ~guess-language-mode~, a minor mode for Emacs that guesses the language of the current paragraph and then changes the dictionary of ispell and the language settings of typo-mode.  It also reruns Flyspell on the current paragraph, but only on that paragraph because I want to leave paragraphs in other languages untouched.  Language guessing is triggered when Flyspell detects an unknown word, but only if the paragraph has enough material to allow for robust detection of the language (~ 35 characters).

Currently, the following languages are supported: Czech, Dansk, Dutch, English, Finnish, French, German, Italian, Norwegian, Polish, Portuguese, Russian, Slovak, Slovenian, Swedish.  It is very easy to add more languages and this repository includes the necessary language statistics for 49 additional languages.  (These were copied from [[https://github.com/kent37/guess-language][guess_language.py]].)

** Prerequisites

This mode assumes that Flyspell is activated and configured for all relevant languages, i.e., those listed in ~guess-language-languages~.  Guess-language also assumes that [[https://github.com/jorgenschaefer/typoel][typo-mode]] is installed and set up.

** Configuration

#+BEGIN_SRC elisp
(require 'guess-language)

;; Optionally:
(setq guess-language-languages '(en de))
(setq guess-language-min-paragraph-length 35)
#+END_SRC

Available languages at this time:

| IDO 639-1 code | Language   |
|----------------+------------|
| ~cs~           | Czech      |
| ~da~           | Dansk      |
| ~nl~           | Dutch      |
| ~en~           | English    |
| ~fi~           | Finnish    |
| ~fr~           | French     |
| ~de~           | German     |
| ~it~           | Italian    |
| ~nb~           | Norwegian  |
| ~pl~           | Polish     |
| ~pt~           | Portuguese |
| ~ru~           | Russian    |
| ~sk~           | Slovak     |
| ~sl~           | Slovenian  |
| ~sv~           | Swedish    |

** Usage

Activate ~guess-language-mode~ in the buffer in which you want to use it.  To activate it automatically in buffers containing text (as opposed to code), add guess-language mode to ~text-mode-hook~:

#+BEGIN_SRC elisp
(add-hook 'text-mode-hook (lambda () (guess-language-mode 1)))
#+END_SRC
